trigger:
  branches:
    include:
      - refs/heads/*
    exclude:
      - refs/tags/*
  paths:
    exclude:
      - README.md
      - LICENSE
      - CODE_OF_CONDUCT.md
      - CONTRIBUTING.md

jobs:
  - template: templates/jobs.yml
    parameters:
      name: macOS
      vmImage: 'macOS-latest'
