trigger:
  branches:
    include:
      - refs/tags/*
    exclude:
      - refs/heads/*

stages:
  - stage: Tests
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
    jobs:
    - template: templates/jobs.yml
      parameters:
        name: Linux
        vmImage: 'ubuntu-latest'
    - template: templates/jobs.yml
      parameters:
        name: Windows
        vmImage: 'windows-latest'
    - template: templates/jobs.yml
      parameters:
        name: macOS
        vmImage: 'macOS-latest'
  - stage: Publish
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
    dependsOn: Tests
    jobs:
      - template: templates/publish.yml
